os: linux
arch: arm64-graviton2
dist: focal
virt: vm
group: edge
language: cpp

install:
  - sudo curl --create-dirs -SLo /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-arm64
  - sudo chmod +x /usr/local/bin/bazel
  - sudo apt-get install -y openjdk-8-jdk
script:
  - ./build_zetasql_parser.sh

before_deploy:
  - TAG=${TRAVIS_TAG#v} ./pack_zetasql.sh

deploy:
  provider: releases
  api_key:
    # steps to produce a encrypted key from GitHub
    # 1. generate a personal access token at https://github.com/settings/tokens, select only repo:public_repo
    # 2. generate && copy the token
    # 3. install travis && run 'travis encrypt <token string> --com'
    # 4. replace below line with the output
    secure: "RmzUGAPO3Gi0mXtG/4mUlPGxLu6Fp21oD6NifJV5FnPPmAFIvLU62WU4xzd/Gyt0FKQThoopT1nQRYbOUtkCLRWgXh/qwRRAyymxJlvpoKOk1bCrKBL2Zr3J7YlS8zEYj9SiFEfkFgs+1laW9ddlyk8rU5OO4XvTU0R/zcoecTkiZqpYiHOZsvy+mnwBfacbZuzjS5VjP8Vbh3ut1+yJdYaERYY6EZJ4dQSQeNGTact7BeuNPD/HDxPkuHs1sdcby/N2r6yDaQp59wrzOuTmgVJJlxaU7nBhpT8rmkQKp782lEqTZnu/606aSj0/ArNvVOo5XXUz3ttl4xQleP65/g2OqDi74yc02gHRrN2srz/oUKJX2bqN3KxYvG2LbniHdsFtDa6Yc9jsyc2p9LjSgkAYcM61qPdokWDlEBUdV1wHYfC2oQ/Z8vuMcabynKsg0si9MdoMsu4qUrh/S0QnpxIqX7cSj1azIiHlY1AIttU7/e3DNi6cvOTJAHWCEH7JPAqcLuYh/8rk0oM0qxzc8ttT76XPUc8tOcGj9h0nu7BPQ7ZbzpKeCrNajLWRj3tELbmMw5IT1mJtoRSR1o+pDT1vyCZ9BeSHJvq75WSJphVq4EKpgsNodkEsKCdBsJQx9GdZLv79lcknbTnS8FgurpvVu6P90C1CTAQLtmdR8t8="
  file_glob: true
  file: libzetasql-*.tar.gz
  skip_cleanup: true
  on:
    tags: true
