# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev, macos ]
  pull_request:
    brancheds: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mac-build:
    strategy:
      fail-fast: false
      matrix:
        container: ['macos:10.15', 'macos:10.14', 'macos:10.13', 'macos:10.12']
    runs-on: ${{ matrix.container }}
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2

      - name: install bazelisk
        run: |
          brew install bazelisk

      - name: print toolchain info
        run: |
          system_profiler SPSoftwareDataType
          gcc -v
          g++ -v
          python -V
          java -version

      - name: build
        run: |
          bazel --version
          bazel build ...

      - name: test
        run: |
          bazel test --test_summary=detailed ...
